import { AppLanguage } from '../types';

export const translations = {
  English: {
    title: 'CivicLens',
    tagline: 'See it. Post it. Solve it.',
    subtagline: 'A citizen-powered civic issue reporting & resolution platform',
    navHome: 'AI-Clustered Feed',
    navAllPosts: 'All Reports',
    navPostIssue: 'Report Hazard',
    navDashboard: 'Impact Dashboard',
    navSolved: 'Solved Issues',
    navProfile: 'My Profile',
    selectState: 'Select State',
    selectCity: 'Select City',
    filterRecent: 'Recents',
    filterVerified: 'Status-Verified',
    sortBySeverity: 'Sort: High → Low Severity',
    prevailing: 'Prevailing Issue',
    tackled: 'Tackled Issue',
    reportedBy: 'Reported by',
    dimensions: 'Rough Dimensions',
    verifiedTag: 'Verified Tag',
    notVerified: 'Pending Votes',
    forwardedTo: 'Auto-forwarded to',
    addComment: 'Add issue-oriented detail...',
    commentNotice: 'AI Comment Moderation is Active. Casual chatter and unconstructive comments are automatically filtered.',
    submit: 'Publish Report',
    step: 'Step',
    next: 'Next',
    back: 'Back',
    aiSuggesting: 'AI Auto-Detecting...',
    aiDetected: 'AI Detection Complete',
    reputation: 'Civic Reputation Points',
    badgesEarned: 'Badges Earned',
    createCommunityBtn: 'Create Action Group',
    communityTitle: 'Community Action Groups',
    noCommunities: 'No communities active for this city yet.',
    smartMergeTitle: 'Severity Smart Merge Engine',
    smartMergeDesc: 'When multiple citizens report the same issue, CivicLens resolves differences using a smart combination algorithm:',
    viewConflict: 'View Reports Merge',
    voteQuestion1: "If it's true — is this a real issue?",
    voteQuestion2: "If it's true — is this issue now resolved?",
    yes: 'YES',
    no: 'NO',
    thankYouVote: 'Thank you for your vote! Votes are recorded non-anonymously.',
    roleCitizen: 'Citizen',
    roleNGO: 'NGO Coordinator',
    roleOfficer: 'Municipal Officer',
    activeUser: 'Active Session',
    cameraSim: 'Camera Simulation',
    choosePhoto: 'Select a sample photo to upload',
    voicePostBtn: 'Use Voice-based Posting',
    recording: 'Listening... Speak now',
    gpsFetch: 'Fetch GPS Location',
    gpsFetching: 'Fetching GPS coordinates...',
    gpsSuccess: 'GPS Location Captured!',
    civicHealth: 'City Civic Health Score',
    resolutionTime: 'Avg Resolution Time',
    totalReported: 'Total Hazards Logged',
    totalSolved: 'Successfully Tackled',
    totalVerified: 'Community Verified',
    forwardStatus: 'Forwarding Telemetry Logs',
    roleSwitcher: 'Switch Demo Role',
    navHomePage: 'Home page',
    navCommunityGroups: 'Action Groups',
    navLogin: 'Sign Up / Login',
    seeItPostIt: 'See it. Post it. Solve it.',
    aboutPlatform: 'CivicLens is a non-anonymous, AI-assisted civic issue reporting platform where citizens, NGOs, and municipal bodies come together as responsible social participants to report, verify, and resolve city problems.',
    stepToMake: 'Step to make',
    passiveToActive: 'Passive citizens into active civic guardians',
    explorePlatform: 'Explore CivicLens Platform',
    directActionPortals: 'Direct action portals for active civic guardians',
    aiClusteredFeedDesc: 'Browse localized city hazards auto-clustered by AI to eliminate duplicates and organize consensus.',
    allReportsDesc: 'Access the exhaustive database of municipal hazard reports, track resolutions, and vote on verifications.',
    reportHazardDesc: 'File a new municipal issue with live GPS coordinates, high-precision image analysis, and severity rating.',
    actionGroupsDesc: 'Join grassroots NGO movements, enlist as local volunteer squads, and coordinate direct ground support.',
    communityFeedback: 'Community Feedback',
    partnerTestimonials: 'Partner Testimonials',
    collabDesc: 'See how citizens, grassroot NGOs, and Municipal officers collaborate through CivicLens to resolve municipal hazards in record time.',
    priyaQuote: '"CivicLens is a game-changer! I reported a massive asphalt pothole near the central main road. Within 3 days, it got verified and fixed. Exceptional tool!"',
    ecoQuote: '"The AI clustering and duplicate detection prevent waste. We can now allocate volunteers with 100% precision to plant saplings or clean waste."',
    officerQuote: '"The real-time coordinate validation and high-precision photos allow BBMP crews to address high-severity streetlamp issues rapidly. Stellar tool for trust!"',
    unlockInteractiveFeed: 'Unlock Interactive Feed',
    joinConsensusTitle: 'Join our active consensus network today',
    joinConsensusDesc: 'Log road hazards, verify duplicate reports using AI, participate in community actions, and coordinate directly with local municipal bodies and NGOs.',
    loginSignUpNow: 'Login / Sign Up now',
    enterFeed: 'Enter Feed',
    viewDatabase: 'View Database',
    fileReport: 'File Report',
    joinGroups: 'Join Groups',
    corporationAuthority: 'Corporation Authority',
    environmentalPartner: 'Environmental Partner',
    activeCitizen: 'Active Citizen (HSR Layout)',
    municipalCommissioner: 'Municipal Commissioner'
  },
  Hindi: {
    title: 'सिविक लेंस (CivicLens)',
    tagline: 'देखें। पोस्ट करें। सुलझाएं।',
    subtagline: 'एक नागरिक-संचालित नागरिक समस्या रिपोर्टिंग और समाधान मंच',
    navHome: 'AI-क्लस्टर फीड',
    navAllPosts: 'सभी रिपोर्ट',
    navPostIssue: 'समस्या की रिपोर्ट करें',
    navDashboard: 'प्रभाव डैशबोर्ड',
    navSolved: 'सुलझी हुई समस्याएं',
    navProfile: 'मेरी प्रोफ़ाइल',
    selectState: 'राज्य चुनें',
    selectCity: 'शहर चुनें',
    filterRecent: 'हाल के',
    filterVerified: 'स्थिति-सत्यापित',
    sortBySeverity: 'सॉर्ट: उच्च → निम्न गंभीरता',
    prevailing: 'सक्रिय समस्या',
    tackled: 'सुलझाई गई समस्या',
    reportedBy: 'द्वारा रिपोर्ट किया गया',
    dimensions: 'मोटे तौर पर आयाम',
    verifiedTag: 'सत्यापित टैग',
    notVerified: 'सत्यापन लंबित',
    forwardedTo: 'स्वतः प्रेषित किया गया',
    addComment: 'समस्या-उन्मुख विवरण जोड़ें...',
    commentNotice: 'AI टिप्पणी मॉडरेशन सक्रिय है। अनौपचारिक चैट और अनुपयोगी टिप्पणियों को स्वतः फ़िल्टर किया जाता है।',
    submit: 'रिपोर्ट प्रकाशित करें',
    step: 'कदम',
    next: 'आगे',
    back: 'पीछे',
    aiSuggesting: 'AI स्वतः पता लगा रहा है...',
    aiDetected: 'AI पहचान पूर्ण',
    reputation: 'नागरिक प्रतिष्ठा अंक',
    badgesEarned: 'अर्जित बैज',
    createCommunityBtn: 'कार्रवाई समूह बनाएं',
    communityTitle: 'सामुदायिक कार्रवाई समूह',
    noCommunities: 'इस शहर के लिए अभी तक कोई समुदाय सक्रिय नहीं है।',
    smartMergeTitle: 'गंभीरता स्मार्ट मर्ज इंजन',
    smartMergeDesc: 'जब कई नागरिक एक ही समस्या की रिपोर्ट करते हैं, तो सिविक लेंस एक स्मार्ट एल्गोरिदम का उपयोग करके मतभेदों को सुलझाता है:',
    viewConflict: 'रिपोर्ट मर्ज देखें',
    voteQuestion1: 'यदि यह सच है — क्या यह वास्तविक समस्या है?',
    voteQuestion2: 'यदि यह सच है — क्या यह समस्या अब सुलझ गई है?',
    yes: 'हाँ',
    no: 'नहीं',
    thankYouVote: 'आपके वोट के लिए धन्यवाद! वोट गैर-अनाम रूप से दर्ज किए जाते हैं।',
    roleCitizen: 'नागरिक',
    roleNGO: 'NGO समन्वयक',
    roleOfficer: 'नगर पालिका अधिकारी',
    activeUser: 'सक्रिय सत्र',
    cameraSim: 'कैमरा सिमुलेशन',
    choosePhoto: 'अपलोड करने के लिए एक नमूना फोटो चुनें',
    voicePostBtn: 'आवाज-आधारित पोस्टिंग का उपयोग करें',
    recording: 'सुन रहा हूँ... अब बोलें',
    gpsFetch: 'GPS स्थान प्राप्त करें',
    gpsFetching: 'GPS निर्देशांक प्राप्त कर रहा है...',
    gpsSuccess: 'GPS स्थान सफलतापूर्वक प्राप्त हुआ!',
    civicHealth: 'शहर नागरिक स्वास्थ्य स्कोर',
    resolutionTime: 'औसत समाधान समय',
    totalReported: 'कुल दर्ज की गई समस्याएं',
    totalSolved: 'सफलतापूर्वक सुलझाया गया',
    totalVerified: 'समुदाय द्वारा सत्यापित',
    forwardStatus: 'टेलीमेट्री लॉग अग्रेषण',
    roleSwitcher: 'डेमो भूमिका बदलें',
    navHomePage: 'मुख्य पृष्ठ',
    navCommunityGroups: 'कार्रवाई समूह',
    navLogin: 'साइन अप / लॉगिन',
    seeItPostIt: 'देखें। पोस्ट करें। सुलझाएं।',
    aboutPlatform: 'सिविक लेंस एक गैर-अनाम, एआई-सहायता प्राप्त नागरिक समस्या रिपोर्टिंग मंच है जहां नागरिक, एनजीओ और नगर पालिका निकाय एक साथ आकर शहर की समस्याओं की रिपोर्ट, सत्यापन और समाधान करते हैं।',
    stepToMake: 'बदलाव की दिशा में कदम',
    passiveToActive: 'निष्क्रिय नागरिकों को सक्रिय नागरिक संरक्षकों में बदलना',
    explorePlatform: 'सिविक लेंस मंच का अन्वेषण करें',
    directActionPortals: 'सक्रिय नागरिक संरक्षकों के लिए प्रत्यक्ष कार्रवाई पोर्टल',
    aiClusteredFeedDesc: 'डुप्लिकेट को समाप्त करने और आम सहमति व्यवस्थित करने के लिए एआई द्वारा स्वतः-क्लस्टर किए गए स्थानीयकृत खतरों को ब्राउज़ करें।',
    allReportsDesc: 'नगर निगम के खतरों की रिपोर्ट के संपूर्ण डेटाबेस तक पहुंचें, समाधान ट्रैक करें, और सत्यापन पर वोट करें।',
    reportHazardDesc: 'लाइव जीपीएस निर्देशांक, उच्च-सटीक छवि विश्लेषण और गंभीरता रेटिंग के साथ एक नई समस्या दर्ज करें।',
    actionGroupsDesc: 'जमीनी स्तर के एनजीओ आंदोलनों में शामिल हों, स्थानीय स्वयंसेवक दस्तों के रूप में सूचीबद्ध हों, और सीधे जमीनी सहायता का समन्वय करें।',
    communityFeedback: 'सामुदायिक प्रतिक्रिया',
    partnerTestimonials: 'सहयोगी अनुभवपत्र',
    collabDesc: 'देखें कि कैसे नागरिक, जमीनी स्तर के एनजीओ और नगर निगम के अधिकारी रिकॉर्ड समय में खतरों को हल करने के लिए मिलकर सहयोग करते हैं।',
    priyaQuote: '"सिविक लेंस एक गेम-चेंजर है! मैंने केंद्रीय मुख्य सड़क के पास एक विशाल गड्ढे की रिपोर्ट की। 3 दिनों के भीतर, इसका सत्यापन किया गया और इसे ठीक कर दिया गया। असाधारण उपकरण!"',
    ecoQuote: '"एआई क्लस्टरिंग और डुप्लिकेट पहचान समय और संसाधनों की बर्बादी को रोकती है। अब हम पेड़ लगाने या कचरा साफ करने के लिए 100% सटीकता के साथ स्वयंसेवकों को आवंटित कर सकते हैं।"',
    officerQuote: '"वास्तविक समय निर्देशांक सत्यापन और उच्च-सटीक तस्वीरें हमारे कर्मचारियों को उच्च-गंभीरता वाले मुद्दों का तेजी से समाधान करने की अनुमति देती हैं। विश्वास के लिए उत्कृष्ट उपकरण!"',
    unlockInteractiveFeed: 'इंटरैक्टिव फीड अनलॉक करें',
    joinConsensusTitle: 'आज ही हमारे सक्रिय आम सहमति नेटवर्क से जुड़ें',
    joinConsensusDesc: 'सड़क के खतरों को लॉग करें, एआई का उपयोग करके डुप्लिकेट रिपोर्ट सत्यापित करें, सामुदायिक कार्यों में भाग लें और स्थानीय नगर निकायों और एनजीओ के साथ सीधे समन्वय करें।',
    loginSignUpNow: 'अभी लॉगिन / साइन अप करें',
    enterFeed: 'फीड में प्रवेश करें',
    viewDatabase: 'डेटाबेस देखें',
    fileReport: 'रिपोर्ट दर्ज करें',
    joinGroups: 'समूहों में शामिल हों',
    corporationAuthority: 'नगर निगम प्राधिकरण',
    environmentalPartner: 'पर्यावरण सहयोगी',
    activeCitizen: 'सक्रिय नागरिक (एचएसआर लेआउट)',
    municipalCommissioner: 'नगर आयुक्त'
  },
  Spanish: {
    title: 'CivicLens',
    tagline: 'Míralo. Publícalo. Resuélvelo.',
    subtagline: 'Plataforma de reporte y resolución de problemas cívicos impulsada por ciudadanos',
    navHome: 'Feed Clustered por IA',
    navAllPosts: 'Todos los Reportes',
    navPostIssue: 'Reportar Problema',
    navDashboard: 'Tablero de Impacto',
    navSolved: 'Problemas Resueltos',
    navProfile: 'Mi Perfil',
    selectState: 'Seleccionar Estado',
    selectCity: 'Seleccionar Ciudad',
    filterRecent: 'Recientes',
    filterVerified: 'Estado Verificado',
    sortBySeverity: 'Filtrar: Severidad Alta → Baja',
    prevailing: 'Problema Pendiente',
    tackled: 'Problema Resuelto',
    reportedBy: 'Reportado por',
    dimensions: 'Dimensiones Aproximadas',
    verifiedTag: 'Etiqueta Verificada',
    notVerified: 'Votos Pendientes',
    forwardedTo: 'Auto-enviado a',
    addComment: 'Añadir detalle sobre el problema...',
    commentNotice: 'La moderación de comentarios de IA está activa. El chat casual e improductivo se filtra automáticamente.',
    submit: 'Publicar Reporte',
    step: 'Paso',
    next: 'Siguiente',
    back: 'Anterior',
    aiSuggesting: 'IA Auto-Detectando...',
    aiDetected: 'Detección de IA Completa',
    reputation: 'Puntos de Reputación Cívica',
    badgesEarned: 'Insignias Ganadas',
    createCommunityBtn: 'Crear Grupo de Acción',
    communityTitle: 'Grupos de Acción Comunitaria',
    noCommunities: 'Aún no hay comunidades activas para esta ciudad.',
    smartMergeTitle: 'Motor de Fusión Inteligente de Severidad',
    smartMergeDesc: 'Cuando múltiples ciudadanos reportan el mismo problema, CivicLens resuelve las diferencias mediante un algoritmo de fusión:',
    viewConflict: 'Ver Fusión de Reportes',
    voteQuestion1: 'Si es verdad — ¿es este un problema real?',
    voteQuestion2: 'Si es verdad — ¿se ha resuelto ya?',
    yes: 'SÍ',
    no: 'NO',
    thankYouVote: '¡Gracias por su voto! Los votos se registran de forma no anónima.',
    roleCitizen: 'Ciudadano',
    roleNGO: 'Coordinador de ONG',
    roleOfficer: 'Oficial Municipal',
    activeUser: 'Sesión Activa',
    cameraSim: 'Simulación de Cámara',
    choosePhoto: 'Seleccione una foto de muestra para cargar',
    voicePostBtn: 'Usar publicación por voz',
    recording: 'Escuchando... Hable ahora',
    gpsFetch: 'Obtener Ubicación GPS',
    gpsFetching: 'Obteniendo coordenadas GPS...',
    gpsSuccess: '¡Ubicación GPS capturada!',
    civicHealth: 'Puntuación de Salud Cívica',
    resolutionTime: 'Tiempo Promedio de Resolución',
    totalReported: 'Total de Reportes',
    totalSolved: 'Resueltos con Éxito',
    totalVerified: 'Verificados por la Comunidad',
    forwardStatus: 'Telemetría de Envío de Logs',
    roleSwitcher: 'Cambiar Rol de Demostración'
  },
  Tamil: {
    title: 'CivicLens',
    tagline: 'பார். பதிவிடு. தீர்.',
    subtagline: 'குடிமக்கள் மூலமாக நகர்ப்புற பிரச்சினைகளைத் தீர்க்கும் தளம்',
    navHome: 'AI-தொகுப்பு ஊட்டம்',
    navAllPosts: 'அனைத்து அறிக்கைகள்',
    navPostIssue: 'புகார் செய்',
    navDashboard: 'தாக்கத் டாஷ்போர்டு',
    navSolved: 'தீர்க்கப்பட்டவை',
    navProfile: 'எனது சுயவிவரம்',
    selectState: 'மாநிலம் தேர்ந்தெடு',
    selectCity: 'நகரம் தேர்ந்தெடு',
    filterRecent: 'அண்மையவை',
    filterVerified: 'சரிபார்க்கப்பட்டது',
    sortBySeverity: 'வகைப்படுத்து: அதிக → குறைந்த தீவிரம்',
    prevailing: 'நடப்பு பிரச்சினை',
    tackled: 'தீர்க்கப்பட்ட பிரச்சினை',
    reportedBy: 'பதிவிட்டவர்',
    dimensions: 'தோராயமான அளவுகள்',
    verifiedTag: 'சரிபார்க்கப்பட்ட முத்திரை',
    notVerified: 'வாக்கு நிலுவையில்',
    forwardedTo: 'தானாக அனுப்பப்பட்டது',
    addComment: 'பிரச்சினை தொடர்பான விவரத்தைச் சேர்க்கவும்...',
    commentNotice: 'AI கருத்து நிர்வகிப்பு செயல்பாட்டில் உள்ளது. தேவையற்ற அரட்டைகள் தானாகவே வடிகட்டப்படும்.',
    submit: 'அறிக்கையை வெளியிடு',
    step: 'படி',
    next: 'அடுத்து',
    back: 'முந்தைய',
    aiSuggesting: 'AI கண்டறிகிறது...',
    aiDetected: 'AI கண்டறிதல் முடிந்தது',
    reputation: 'குடிமகன் நற்பெயர் புள்ளிகள்',
    badgesEarned: 'பெற்ற பதக்கங்கள்',
    createCommunityBtn: 'செயல் குழுவை உருவாக்கு',
    communityTitle: 'சமூக செயல் குழுக்கள்',
    noCommunities: 'இந்த நகரத்திற்கு இன்னும் குழுக்கள் எதுவும் இல்லை.',
    smartMergeTitle: 'தீவிர ஸ்மார்ட் இணைப்பு இயந்திரம்',
    smartMergeDesc: 'ஒரே பிரச்சினையைப் பல குடிமக்கள் புகாரளிக்கும் போது, CivicLens ஒரு ஸ்மார்ட் அல்காரிதம் மூலம் முரண்பாடுகளைத் தீர்க்கிறது:',
    viewConflict: 'அறிக்கைகளின் இணைப்பைப் பார்',
    voteQuestion1: 'இது உண்மை என்றால் — இது ஒரு உண்மையான பிரச்சினையா?',
    voteQuestion2: 'இது உண்மை என்றால் — இப்பிரச்சினை தீர்க்கப்பட்டுவிட்டதா?',
    yes: 'ஆம்',
    no: 'இல்லை',
    thankYouVote: 'உங்கள் வாக்கிற்கு நன்றி! வாக்குகள் அநாமதேயமின்றி பதிவு செய்யப்படுகின்றன.',
    roleCitizen: 'குடிமகன்',
    roleNGO: 'அறக்கட்டளை ஒருங்கிணைப்பாளர்',
    roleOfficer: 'நகராட்சி அதிகாரி',
    activeUser: 'செயலில் உள்ள அமர்வு',
    cameraSim: 'கேமரா உருவகப்படுத்துதல்',
    choosePhoto: 'பதிவேற்ற ஒரு மாதிரியைத் தேர்வு செய்க',
    voicePostBtn: 'குரல் மூலம் பதிவிடவும்',
    recording: 'கேட்கிறது... இப்போது பேசவும்',
    gpsFetch: 'GPS இருப்பிடத்தைப் பெறு',
    gpsFetching: 'GPS ஆயங்களை வாங்குகிறது...',
    gpsSuccess: 'GPS இருப்பிடம் வெற்றிகரமாகப் பெறப்பட்டது!',
    civicHealth: 'நகர சுகாதார மதிப்பெண்',
    resolutionTime: 'சராசரி தீர்வு காலம்',
    totalReported: 'பதிவு செய்யப்பட்ட மொத்தப் பிரச்சினைகள்',
    totalSolved: 'வெற்றிகரமாகத் தீர்க்கப்பட்டவை',
    totalVerified: 'சமூகத்தால் சரிபார்க்கப்பட்டவை',
    forwardStatus: 'டெலிமெட்ரி பதிவுகள் அனுப்புதல்',
    roleSwitcher: 'டெமோ பாத்திரத்தை மாற்று'
  },
  Marathi: {
    title: 'CivicLens',
    tagline: 'बघा. पोस्ट करा. सोडवा.',
    subtagline: 'नागरिक-चालित नागरी समस्या नोंदणी व निवारण मंच',
    navHome: 'AI-क्लस्टर फीड',
    navAllPosts: 'सर्व अहवाल',
    navPostIssue: 'समस्या नोंदवा',
    navDashboard: 'प्रभाव डॅशबोर्ड',
    navSolved: 'सोडवलेल्या समस्या',
    navProfile: 'माझी प्रोफाइल',
    selectState: 'राज्य निवडा',
    selectCity: 'शहर निवडा',
    filterRecent: 'नुकतेच',
    filterVerified: 'स्थिती-सत्यापित',
    sortBySeverity: 'क्रम लावा: उच्च → कमी तीव्रता',
    prevailing: 'सक्रिय समस्या',
    tackled: 'निवारण झालेली समस्या',
    reportedBy: 'द्वारे नोंदवले गेले',
    dimensions: 'अंदाजे आकारमान',
    verifiedTag: 'सत्यापित टॅग',
    notVerified: 'सत्यापन प्रलंबित',
    forwardedTo: 'स्वयंचलितपणे पाठवले',
    addComment: 'समस्या-देणारं तपशील जोडा...',
    commentNotice: 'AI टिप्पणी नियंत्रण सुरू आहे. निरर्थक गप्पा आणि निरुपयोगी टिप्पण्या स्वयंचलितपणे गाळल्या जातात.',
    submit: 'अहवाल प्रकाशित करा',
    step: 'पायरी',
    next: 'पुढे',
    back: 'मागे',
    aiSuggesting: 'AI शोध घेत आहे...',
    aiDetected: 'AI ओळख पूर्ण झाली',
    reputation: 'नागरी प्रतिष्ठा गुण',
    badgesEarned: 'मिळालेले बॅज',
    createCommunityBtn: 'कृती गट तयार करा',
    communityTitle: 'सामुदायिक कृती गट',
    noCommunities: 'या शहरासाठी अद्याप कोणतेही समुदाय सक्रिय नाहीत.',
    smartMergeTitle: 'तीव्रता स्मार्ट मर्ज इंजिन',
    smartMergeDesc: 'जेव्हा एकाच समस्येची अनेक नागरिकांकडून नोंद केली जाते, तेव्हा CivicLens एका विशेष अल्गोरिदमने फरक सोडवते:',
    viewConflict: 'अहवाल विलीनीकरण पहा',
    voteQuestion1: 'हे सत्य असल्यास — ही खरोखरच समस्या आहे का?',
    voteQuestion2: 'हे सत्य असल्यास — या समस्येचे आता निवारण झाले आहे का?',
    yes: 'होय',
    no: 'नाही',
    thankYouVote: 'तुमच्या मतासाठी धन्यवाद! मते पारदर्शकपणे नोंदवली जातात.',
    roleCitizen: 'नागरिक',
    roleNGO: 'NGO समन्वयक',
    roleOfficer: 'नगरपालिका अधिकारी',
    activeUser: 'सक्रिय सत्र',
    cameraSim: 'कॅमेरा सिम्युलेशन',
    choosePhoto: 'अपलोड करण्यासाठी नमुना फोटो निवडा',
    voicePostBtn: 'आवाज-आधारित पोस्टिंग वापरा',
    recording: 'ऐकत आहे... आता बोला',
    gpsFetch: 'GPS स्थान मिळवा',
    gpsFetching: 'GPS स्थान शोधत आहे...',
    gpsSuccess: 'GPS स्थान यशस्वीरित्या मिळाले!',
    civicHealth: 'शहर नागरी आरोग्य गुण',
    resolutionTime: 'सरासरी निवारण वेळ',
    totalReported: 'एकूण नोंदवलेल्या समस्या',
    totalSolved: 'यशस्वीरित्या सोडवलेल्या',
    totalVerified: 'समुदायाने प्रमाणित केलेल्या',
    forwardStatus: 'टेलीमेट्री लॉग पाठवणे',
    roleSwitcher: 'डेमो भूमिका बदला'
  }
};

export function getTranslation(lang: AppLanguage, key: keyof typeof translations['English']): string {
  const currentLangDict = translations[lang] || translations['English'];
  return (currentLangDict[key] || translations['English'][key]) as string;
}
